#!/bin/bash
#
# Phase 04: Wi-Fi Access Point Setup
# Configures hostapd and dnsmasq for AP mode
#

set -euo pipefail

echo "[04-wifi-ap] Starting Wi-Fi AP configuration..."

# Configuration from environment
WIFI_SSID="${WIFI_SSID:-photobooth}"
WIFI_PASSWORD="${WIFI_PASSWORD:-photobooth-1998}"
WIFI_CHANNEL="${WIFI_CHANNEL:-6}"
PI_IP="${PI_IP:-192.168.4.1}"
DHCP_RANGE_START="${DHCP_RANGE_START:-192.168.4.10}"
DHCP_RANGE_END="${DHCP_RANGE_END:-192.168.4.50}"
COUNTRY_CODE="${COUNTRY_CODE:-RW}"

echo "Configuration:"
echo "  SSID: $WIFI_SSID"
echo "  Channel: $WIFI_CHANNEL"
echo "  Pi IP: $PI_IP"
echo "  DHCP Range: $DHCP_RANGE_START - $DHCP_RANGE_END"

# Install required packages
echo "Installing hostapd and dnsmasq..."
apt-get install -y -qq hostapd dnsmasq

# Stop services during configuration
echo "Stopping services for configuration..."
systemctl stop hostapd 2>/dev/null || true
systemctl stop dnsmasq 2>/dev/null || true

# Unblock WiFi
echo "Unblocking WiFi..."
rfkill unblock wifi

# Configure static IP for wlan0
echo "Configuring static IP..."

# Check if already configured
if grep -q "# PhotoBooth Wi-Fi AP" /etc/dhcpcd.conf 2>/dev/null; then
    echo "Static IP already configured in dhcpcd.conf"
else
    cat >> /etc/dhcpcd.conf << EOF

# PhotoBooth Wi-Fi AP Static IP Configuration
interface wlan0
    static ip_address=${PI_IP}/24
    nohook wpa_supplicant
EOF
fi

# Configure hostapd
echo "Configuring hostapd..."

cat > /etc/hostapd/hostapd.conf << EOF
# PhotoBooth Wi-Fi Access Point Configuration
# Auto-generated by setup script

interface=wlan0
driver=nl80211

# Network settings
ssid=${WIFI_SSID}
hw_mode=g
channel=${WIFI_CHANNEL}
country_code=${COUNTRY_CODE}

# 802.11n support
ieee80211n=1
wmm_enabled=0

# Security
auth_algs=1
wpa=2
wpa_passphrase=${WIFI_PASSWORD}
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP

# Visibility and limits
ignore_broadcast_ssid=0
max_num_sta=10

# Logging
logger_syslog=-1
logger_syslog_level=2
logger_stdout=-1
logger_stdout_level=2
EOF

chmod 600 /etc/hostapd/hostapd.conf

# Point hostapd daemon to config
if grep -q "^#DAEMON_CONF" /etc/default/hostapd 2>/dev/null; then
    sed -i 's|^#DAEMON_CONF=.*|DAEMON_CONF="/etc/hostapd/hostapd.conf"|' /etc/default/hostapd
elif ! grep -q "^DAEMON_CONF" /etc/default/hostapd 2>/dev/null; then
    echo 'DAEMON_CONF="/etc/hostapd/hostapd.conf"' >> /etc/default/hostapd
fi

# Configure dnsmasq
echo "Configuring dnsmasq..."

# Backup original config if exists
if [[ -f /etc/dnsmasq.conf ]] && [[ ! -f /etc/dnsmasq.conf.orig ]]; then
    mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig
fi

cat > /etc/dnsmasq.conf << EOF
# PhotoBooth DHCP and DNS Configuration
# Auto-generated by setup script

# Interface
interface=wlan0
bind-interfaces

# DHCP configuration
dhcp-range=${DHCP_RANGE_START},${DHCP_RANGE_END},255.255.255.0,24h
dhcp-option=option:router,${PI_IP}
dhcp-option=option:dns-server,${PI_IP}

# DNS configuration
domain=photobooth.local
local=/photobooth.local/

# Resolve photobooth.local to Pi's IP
address=/photobooth.local/${PI_IP}

# Captive portal - all DNS queries resolve to Pi
# This allows any URL to reach the photo booth
address=/#/${PI_IP}

# Operational settings
dhcp-leasefile=/var/lib/misc/dnsmasq.leases
log-queries
log-dhcp
no-resolv
no-poll
cache-size=1000
EOF

# Enable IP forwarding (in case needed for routing)
echo "Enabling IP forwarding..."
if ! grep -q "^net.ipv4.ip_forward=1" /etc/sysctl.conf 2>/dev/null; then
    sed -i 's/^#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
    if ! grep -q "^net.ipv4.ip_forward=1" /etc/sysctl.conf; then
        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
    fi
fi
sysctl -w net.ipv4.ip_forward=1

# Unmask and enable services
echo "Enabling services..."
systemctl unmask hostapd
systemctl enable hostapd
systemctl enable dnsmasq

# Restart dhcpcd to apply static IP
echo "Applying static IP configuration..."
systemctl restart dhcpcd

# Wait for IP to be configured
sleep 5

# Start services
echo "Starting Wi-Fi AP services..."
systemctl start hostapd
sleep 2
systemctl start dnsmasq

# Verify services are running
echo "Verifying services..."

if systemctl is-active --quiet hostapd; then
    echo "  hostapd: running"
else
    echo "  hostapd: FAILED"
    journalctl -u hostapd -n 10 --no-pager
fi

if systemctl is-active --quiet dnsmasq; then
    echo "  dnsmasq: running"
else
    echo "  dnsmasq: FAILED"
    journalctl -u dnsmasq -n 10 --no-pager
fi

# Check IP address
echo "Checking network configuration..."
if ip addr show wlan0 | grep -q "$PI_IP"; then
    echo "  wlan0 IP: $PI_IP (configured)"
else
    echo "  wlan0 IP: NOT configured as expected"
    ip addr show wlan0
fi

echo ""
echo "[04-wifi-ap] Wi-Fi AP configuration complete"
echo ""
echo "Wi-Fi Network Details:"
echo "  SSID: $WIFI_SSID"
echo "  Password: $WIFI_PASSWORD"
echo "  Pi IP: $PI_IP"
echo ""
echo "Clients can connect to the '$WIFI_SSID' network"
echo "and access the photo booth at https://$PI_IP"
