#!/bin/bash
#
# Phase 06: Application Deployment
# Deploys the PhotoBooth application
#

set -euo pipefail

echo "[06-deploy] Starting application deployment..."

PHOTOBOOTH_DIR="${PHOTOBOOTH_DIR:-/home/pi/photobooth}"
DATA_DIR="${PHOTOBOOTH_DIR}/data"
SCRIPT_DIR="$(dirname "$0")/.."

# Create directory structure
echo "Creating directory structure..."
mkdir -p "$DATA_DIR/photos"
mkdir -p "$DATA_DIR/composites"
mkdir -p "$DATA_DIR/logs"
mkdir -p "$PHOTOBOOTH_DIR/backups"

# Set permissions
echo "Setting permissions..."
chown -R pi:pi "$PHOTOBOOTH_DIR"
chmod 755 "$DATA_DIR"
chmod 755 "$DATA_DIR/photos"
chmod 755 "$DATA_DIR/composites"
chmod 755 "$DATA_DIR/logs"
chmod 755 "$PHOTOBOOTH_DIR/backups"

# Check if docker-compose.yml exists
if [[ ! -f "$PHOTOBOOTH_DIR/docker-compose.yml" ]]; then
    echo "ERROR: docker-compose.yml not found in $PHOTOBOOTH_DIR"
    echo ""
    echo "Please ensure the PhotoBooth application is copied to $PHOTOBOOTH_DIR"
    echo "The directory should contain:"
    echo "  - docker-compose.yml"
    echo "  - backend/"
    echo "  - frontend/"
    echo ""
    exit 1
fi

# Create .env file if it doesn't exist
if [[ ! -f "$PHOTOBOOTH_DIR/.env" ]]; then
    echo "Creating .env file from template..."

    if [[ -f "$PHOTOBOOTH_DIR/.env.example" ]]; then
        cp "$PHOTOBOOTH_DIR/.env.example" "$PHOTOBOOTH_DIR/.env"
    else
        cat > "$PHOTOBOOTH_DIR/.env" << 'EOF'
# PhotoBooth Environment Configuration
# Auto-generated by setup script

# Security
JWT_SECRET=change-this-to-a-secure-random-string
ADMIN_PIN_HASH=

# Database
DATABASE_URL=sqlite:///data/photobooth.db

# Storage
STORAGE_PATH=/data
MAX_STORAGE_GB=100

# Logging
LOG_LEVEL=info

# Printer
MOCK_PRINTER=false
PRINTER_NAME=Canon_Selphy_CP1500

# Timezone
TZ=Africa/Kigali
EOF
    fi

    # Generate a secure JWT secret
    echo "Generating secure JWT secret..."
    JWT_SECRET=$(openssl rand -base64 32)
    sed -i "s|^JWT_SECRET=.*|JWT_SECRET=$JWT_SECRET|" "$PHOTOBOOTH_DIR/.env"

    chown pi:pi "$PHOTOBOOTH_DIR/.env"
    chmod 600 "$PHOTOBOOTH_DIR/.env"

    echo ""
    echo "IMPORTANT: Please edit $PHOTOBOOTH_DIR/.env to set:"
    echo "  - ADMIN_PIN_HASH (use bcrypt to hash your admin PIN)"
    echo ""
fi

# Generate SSL certificates if not present
if [[ ! -f "$PHOTOBOOTH_DIR/certs/server.crt" ]]; then
    echo "Generating SSL certificates..."

    mkdir -p "$PHOTOBOOTH_DIR/certs"

    if [[ -f "$SCRIPT_DIR/generate-ssl.sh" ]]; then
        bash "$SCRIPT_DIR/generate-ssl.sh"
    else
        # Generate self-signed certificate
        openssl req -x509 \
            -nodes \
            -days 365 \
            -newkey rsa:2048 \
            -keyout "$PHOTOBOOTH_DIR/certs/server.key" \
            -out "$PHOTOBOOTH_DIR/certs/server.crt" \
            -subj "/CN=photobooth.local/O=PhotoBooth/C=RW" \
            -addext "subjectAltName=DNS:photobooth.local,DNS:localhost,IP:192.168.4.1"
    fi

    chown -R pi:pi "$PHOTOBOOTH_DIR/certs"
    chmod 600 "$PHOTOBOOTH_DIR/certs/server.key"
    chmod 644 "$PHOTOBOOTH_DIR/certs/server.crt"
fi

# Pull Docker images
echo "Pulling Docker images (this may take a while)..."
cd "$PHOTOBOOTH_DIR"
sudo -u pi docker compose pull 2>/dev/null || docker compose pull

# Build containers if needed
echo "Building containers..."
sudo -u pi docker compose build 2>/dev/null || docker compose build

# Start containers
echo "Starting containers..."
sudo -u pi docker compose up -d 2>/dev/null || docker compose up -d

# Wait for containers to be ready
echo "Waiting for containers to start..."
sleep 10

# Check container status
echo ""
echo "Container status:"
docker compose ps

# Check if backend is responding
echo ""
echo "Checking backend health..."
for i in {1..30}; do
    if curl -sf http://localhost:8000/api/health &>/dev/null; then
        echo "Backend is healthy!"
        break
    fi
    echo "  Waiting for backend... ($i/30)"
    sleep 2
done

# Check frontend
echo "Checking frontend..."
if curl -sf http://localhost:80 &>/dev/null || curl -sf http://localhost:3000 &>/dev/null; then
    echo "Frontend is responding!"
else
    echo "Warning: Frontend may not be responding yet"
fi

echo ""
echo "[06-deploy] Application deployment complete"
echo ""
echo "The PhotoBooth application is now running."
echo "Access it at:"
echo "  - http://localhost (HTTP)"
echo "  - https://localhost (HTTPS)"
echo "  - https://192.168.4.1 (from Wi-Fi clients)"
